#!/bin/bash
go test -v ./pkg/cli ./pkg/rundeck.v21 ./pkg/httpclient ./pkg/rundeck.v21/responses ./pkg/rundeck.v21/requests ./pkg/rundeck.v19 ./src/rundeck.v12 ./src/rundeck.v13 ./src/rundeck.v17 ./src/rundeck.v18


