#!/bin/bash
go test -v ./pkg/... ./cmd/...
#go test -v ./pkg/cli ./pkg/rundeck ./pkg/httpclient ./pkg/rundeck/responses ./pkg/rundeck/requests ./pkg/rundeck.v19 ./src/rundeck.v12 ./src/rundeck.v13 ./src/rundeck.v17 ./src/rundeck.v18


