#!/bin/bash
if [ -z ${TRAVIS_BUILD_DIR} ]; then
    printf "this should only be run on travis\n"
    exit 1
fi

printf "setting up rundeck locally\n"

export DEBIAN_FRONTEND=noninteractive
echo "deb http://ftp.de.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list
apt-get update
apt-get install -t jessie-backports -yq openjdk-8-jdk
apt-get install -yq openssh-client curl uuid-runtime python3 git
groupadd rundeck
useradd -g rundeck rundeck
curl -L http://dl.bintray.com/rundeck/rundeck-deb/rundeck-2.10.2-1-GA.deb -o /tmp/rundeck.deb; dpkg -i /tmp/rundeck.deb; rm -rf /tmp/rundeck.deb
cp docker/rundeckd.init /etc/init.d/rundeckd
cp docker/admin.aclpolicy /etc/rundeck/admin.aclpolicy
cp docker/apitoken.aclpolicy /etc/rundeck/apitoken.aclpolicy
cp docker/realm.properties /etc/rundeck/realm.properties
cp docker/token.properties /etc/rundeck/token.properties
echo "rundeck.tokens.file=/etc/rundeck/token.properties" >> /etc/rundeck/framework.properties

docker/gitrepo.sh
chmod +x /etc/init.d/rundeckd

/etc/init.d/rundeckd
printf "sleeping 30 seconds to give rundeck time to start\n"
sleep 30